#!/bin/bash
set -euo pipefail

echo "==> Cleaning up for template..."

# Remove SSH host keys (regenerated on first boot)
rm -f /etc/ssh/ssh_host_*
echo "==> Removed SSH host keys"

# Clear machine-id (regenerated by systemd on boot)
truncate -s 0 /etc/machine-id
rm -f /var/lib/dbus/machine-id
echo "==> Cleared machine-id"

# Reset cloud-init state
if command -v cloud-init &>/dev/null; then
    cloud-init clean --logs --seed
    echo "==> Reset cloud-init state"
fi

# Clear packer user's history
rm -f /home/packer/.bash_history
rm -f /root/.bash_history
echo "==> Cleared bash history"

# Clean apt cache
apt-get clean
apt-get autoremove -y
rm -rf /var/lib/apt/lists/*
echo "==> Cleaned apt cache"

# Remove temporary files
rm -rf /tmp/*
rm -rf /var/tmp/*
echo "==> Removed temporary files"

# Truncate log files
find /var/log -type f -exec truncate -s 0 {} \;
echo "==> Truncated log files"

# Remove Packer provisioner files
rm -rf /tmp/files
rm -rf /tmp/scripts
echo "==> Removed provisioner files"

# Sync and clear caches
sync
echo "==> Template cleanup complete!"
