# https://taskfile.dev
version: "3"

vars:
  MKOSI_BASE: mkosi

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ============================================================
  # mkosi - mihomo-gateway
  # ============================================================
  gateway:download:
    desc: Download Mihomo binary
    dir: "{{.MKOSI_BASE}}/mihomo-gateway"
    cmds:
      - bash download-mihomo.sh

  gateway:build:
    desc: Build mihomo-gateway image (requires Linux/WSL2)
    dir: "{{.MKOSI_BASE}}/mihomo-gateway"
    cmds:
      - mkosi build

  gateway:clean:
    desc: Clean mihomo-gateway build output
    dir: "{{.MKOSI_BASE}}/mihomo-gateway"
    cmds:
      - mkosi clean

  # ============================================================
  # Utility tasks
  # ============================================================
  clean:
    desc: Clean all build outputs
    cmds:
      - cmd: rm -rf {{.MKOSI_BASE}}/*/output
        ignore_error: true

  list:
    desc: List available templates
    cmds:
      - cmd: ls -1 {{.MKOSI_BASE}}/
        platforms: [linux, darwin]
      - cmd: dir /B {{.MKOSI_BASE}}
        platforms: [windows]
