# https://taskfile.dev
version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ============================================================
  # NixOS - Build
  # ============================================================
  build:
    desc: Build all NixOS configurations (requires Nix)
    cmds:
      - nix build .#nixosConfigurations.mihomo-gateway.config.system.build.toplevel

  gateway:build:
    desc: Build mihomo-gateway system
    cmds:
      - nix build .#nixosConfigurations.mihomo-gateway.config.system.build.toplevel
      - echo "Output -> ./result"

  gateway:tarball:
    desc: Build mihomo-gateway tarball (CI friendly, no privilege)
    cmds:
      - nix build .#mihomo-gateway-tarball
      - echo "Output -> ./result/tarball/*.tar.xz"

  gateway:image:
    desc: Build mihomo-gateway disk image (requires KVM/privileged)
    cmds:
      - nix build .#mihomo-gateway-image
      - echo "Output -> ./result/*.raw"

  # ============================================================
  # Development
  # ============================================================
  dev:
    desc: Enter development shell with Nix tools
    cmds:
      - nix develop

  fmt:
    desc: Format all Nix files
    cmds:
      - nix fmt

  check:
    desc: Check flake and evaluate configurations
    cmds:
      - nix flake check

  update:
    desc: Update flake.lock
    cmds:
      - nix flake update

  # ============================================================
  # Utility
  # ============================================================
  clean:
    desc: Clean build outputs
    cmds:
      - rm -rf result result-*

  list:
    desc: List available NixOS configurations
    cmds:
      - nix flake show --json | jq -r '.nixosConfigurations | keys[]'
