name: Build and Release

on:
  workflow_dispatch:

env:
  ARTIFACT_NAME: mihomo-gateway

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"

      - name: Build VM image
        run: nix develop -c just build

      - name: Prepare artifact
        id: artifact
        run: |
          IMAGE=$(find -L ./result -name "*.qcow2" -type f)
          SIZE=$(du -h "$IMAGE" | cut -f1)
          SHA256=$(sha256sum "$IMAGE" | awk '{print $1}')

          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "size=$SIZE" >> $GITHUB_OUTPUT
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ github.run_number }}-${{ github.sha }}
          name: v${{ github.run_number }}-${{ github.sha }}
          body: |
            | 字段 | 值 |
            |------|-----|
            | Commit | `${{ github.sha }}` |
            | Size | ${{ steps.artifact.outputs.size }} |
            | SHA256 | `${{ steps.artifact.outputs.sha256 }}` |
          files: ${{ steps.artifact.outputs.image }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
